### ISSUE TITLE
NodeJs 6 & libxmljs 0.14

### ISSUE THREAD

**Issue by kevin-lot** [morou/gulp-xml-editor#14]
Due to https://github.com/libxmljs/libxmljs/issues/421.

We have to update dependancy version. I tested gulp-xml-editor with libxmljs@0.18 without issues. Tests are running fine.
#15

**Comment by perrin4869** [comment]
@iooK I tried sending a PR with this change over a month ago, https://github.com/morou/gulp-xml-editor/pull/13, but I could never get a response from the maintainer... so I took the liberty of forking this project and created [gulp-xml-transformer](https://github.com/perrin4869/gulp-xml-transformer), with support for node 6. Also made many improvements to the codebase. Should be 100% compatible with this module too :)

**Comment by TheCodeDestroyer** [comment]
@perrin4869 Your fork works! Awesomesauce and thank you very much!

**Comment by kevin-lot** [comment]
@perrin4869 Thank you very much.

**Comment by kevin-lot** [comment]
Switch for https://github.com/perrin4869/gulp-xml-transformer,
